<template>
  <div class="mt-1">
    <div class="mb-2 flex items-center text-xs text-gray-500 dark:text-gray-400">
      <span v-if="status === 'running'" class="tool-shimmer flex items-center">
        <Icon name="heroicons-beaker" class="w-3 h-3 me-1 text-gray-400" />
        {{ argName ? t('tools.createEval.draftingNamed', { name: argName }) : t('tools.createEval.drafting') }}
      </span>
      <span v-else-if="success" class="text-gray-700 dark:text-gray-300 flex items-center">
        <Icon name="heroicons-beaker" class="w-3 h-3 me-1 text-purple-400" />
        <span class="align-middle">{{ t('tools.createEval.created') }}</span>
      </span>
      <span v-else class="text-gray-700 dark:text-gray-300 flex items-center">
        <Icon name="heroicons-exclamation-triangle" class="w-3 h-3 me-1 text-gray-400" />
        <span class="align-middle">{{ t('tools.createEval.notCreated') }}</span>
      </span>
    </div>

    <div v-if="success" class="text-xs text-gray-600 dark:text-gray-400">
      <div class="flex items-center py-1 px-1 rounded">
        <NuxtLink :to="`/evals`" class="font-medium text-gray-700 dark:text-gray-300 truncate hover:text-blue-600">
          {{ caseName || t('tools.createEval.unnamed') }}
        </NuxtLink>
        <span v-if="suiteName" class="ms-1.5 text-[9px] px-1 py-0.5 rounded bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400 flex-shrink-0">{{ suiteName }}</span>
        <span v-if="status_field === 'draft'" class="ms-1 text-[9px] px-1 py-0.5 rounded bg-amber-100 text-amber-800 flex-shrink-0">{{ t('tools.createEval.statusDraft') }}</span>
        <span v-else-if="status_field === 'active'" class="ms-1 text-[9px] px-1 py-0.5 rounded bg-green-100 dark:bg-green-900/50 text-green-800 flex-shrink-0">{{ t('tools.createEval.statusActive') }}</span>
        <span v-if="autoGenerated" class="ms-1 text-[9px] px-1 py-0.5 rounded bg-purple-100 dark:bg-purple-950 text-purple-800 flex-shrink-0">{{ t('tools.createEval.autoBadge') }}</span>
      </div>
      <div v-if="message" class="ms-1 mt-0.5 text-[11px] text-gray-500 dark:text-gray-400">{{ message }}</div>
    </div>

    <div v-else-if="status !== 'running'" class="text-xs text-gray-500 dark:text-gray-400 ms-1">
      {{ message || rejectedReason || t('tools.createEval.defaultMessage') }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

interface ToolExecution {
  id: string
  tool_name: string
  status: string
  result_json?: any
  arguments_json?: any
}

const props = defineProps<{ toolExecution: ToolExecution }>()

const status = computed(() => props.toolExecution?.status || '')

const result = computed<any>(() => props.toolExecution?.result_json || {})
const success = computed<boolean>(() => !!result.value?.success)
const caseName = computed<string>(() => result.value?.name || '')
const suiteName = computed<string>(() => result.value?.suite_name || '')
const status_field = computed<string>(() => result.value?.status || '')
const autoGenerated = computed<boolean>(() => !!result.value?.auto_generated)
const message = computed<string>(() => result.value?.message || '')
const rejectedReason = computed<string>(() => result.value?.rejected_reason || '')

const argName = computed<string>(() => {
  return props.toolExecution?.arguments_json?.name || ''
})
</script>

<style scoped>
.tool-shimmer {
  animation: shimmer 1.6s linear infinite;
  background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(160,160,160,0.15) 50%, rgba(0,0,0,0) 100%);
  background-size: 300% 100%;
  background-clip: text;
}
@keyframes shimmer {
  0% { background-position: 0% 0; }
  100% { background-position: 100% 0; }
}
</style>
