"""completions

Revision ID: 000c405d972c
Revises: 952ae269bd2c
Create Date: 2024-08-11 10:06:01.065170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '000c405d972c'
down_revision: Union[str, None] = '952ae269bd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completions',
    sa.Column('id', get_uuid_column(), primary_key=True, default=uuid.uuid4, nullable=False),
    sa.Column('prompt', sa.JSON(), nullable=False),
    sa.Column('completion', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('parent_id', get_uuid_column(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('report_id', get_uuid_column(), nullable=False),
    sa.Column('widget_id', get_uuid_column(), nullable=True),
    sa.Column('step_id', get_uuid_column(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['completions.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completions_id'), 'completions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completions_id'), table_name='completions')
    op.drop_table('completions')
    # ### end Alembic commands ###
