"""excel sheets

Revision ID: 04c2c1e3b151
Revises: 905a08bb2ca7
Create Date: 2024-08-21 15:24:55.563857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column

# revision identifiers, used by Alembic.
revision: str = '04c2c1e3b151'
down_revision: Union[str, None] = '905a08bb2ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_schemas',
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('sheet_index', sa.Integer(), nullable=True),
    sa.Column('file_id', get_uuid_column(), nullable=False),
    sa.Column('id', get_uuid_column(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_schemas_id'), 'sheet_schemas', ['id'], unique=True)
    op.create_index(op.f('ix_sheet_schemas_sheet_index'), 'sheet_schemas', ['sheet_index'], unique=False)
    op.create_index(op.f('ix_sheet_schemas_sheet_name'), 'sheet_schemas', ['sheet_name'], unique=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_sheet_schemas_sheet_name'), table_name='sheet_schemas')
    op.drop_index(op.f('ix_sheet_schemas_sheet_index'), table_name='sheet_schemas')
    op.drop_index(op.f('ix_sheet_schemas_id'), table_name='sheet_schemas')
    op.drop_table('sheet_schemas')
    # ### end Alembic commands ###
