"""add description and summary to data source

Revision ID: 0996f318acf1
Revises: fd7dd5ccc203
Create Date: 2024-11-25 08:45:26.563338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0996f318acf1'
down_revision: Union[str, None] = 'fd7dd5ccc203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conversation_starters', sa.JSON(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('description')
        batch_op.drop_column('conversation_starters')
    # ### end Alembic commands ###
