"""Initial migration

Revision ID: 0c42ed0cd805
Revises: 
Create Date: 2024-08-09 20:56:52.658268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from app.core.types import get_uuid_column

# revision identifiers, used by Alembic.
revision: str = '0c42ed0cd805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cron_schedule', sa.String(), nullable=True),
    sa.Column('id', get_uuid_column(), primary_key=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_slug'), 'reports', ['slug'], unique=False)
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)

    op.create_table('steps',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('id', get_uuid_column(), primary_key=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_slug'), 'steps', ['slug'], unique=False)
    op.create_index(op.f('ix_steps_title'), 'steps', ['title'], unique=False)

    op.create_table('widgets',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', get_uuid_column(), primary_key=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_slug'), 'widgets', ['slug'], unique=False)
    op.create_index(op.f('ix_widgets_title'), 'widgets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widgets_title'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_slug'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_steps_title'), table_name='steps')
    op.drop_index(op.f('ix_steps_slug'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_index(op.f('ix_reports_slug'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
