"""add llm management

Revision ID: 1281b867f169
Revises: 33775ce24806
Create Date: 2024-12-04 06:48:09.110276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1281b867f169'
down_revision: Union[str, None] = '33775ce24806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('use_preset_credentials', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_providers_id'), ['id'], unique=True)

    op.create_table('llm_models',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_models_id'), ['id'], unique=True)

     ### end Alembic commands ###


def downgrade() -> None:

    with op.batch_alter_table('llm_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_models_id'))

    op.drop_table('llm_models')
    with op.batch_alter_table('llm_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_providers_id'))

    op.drop_table('llm_providers')
    # ### end Alembic commands ###
