"""generate completion_blocks and wire to projectmgr

Revision ID: 1576b701e34b
Revises: 2c6238f56d1c
Create Date: 2025-08-24 13:09:52.747295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1576b701e34b'
down_revision: Union[str, None] = '2c6238f56d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_blocks',
    sa.Column('completion_id', sa.String(length=36), nullable=False),
    sa.Column('agent_execution_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('plan_decision_id', sa.String(length=36), nullable=True),
    sa.Column('tool_execution_id', sa.String(length=36), nullable=True),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('loop_index', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['completion_id'], ['completions.id'], ),
    sa.ForeignKeyConstraint(['plan_decision_id'], ['plan_decisions.id'], ),
    sa.ForeignKeyConstraint(['tool_execution_id'], ['tool_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_execution_id', 'source_type', 'plan_decision_id', 'tool_execution_id', name='uq_blocks_source'),
    sa.UniqueConstraint('completion_id', 'block_index', name='uq_blocks_completion_block_index')
    )
    with op.batch_alter_table('completion_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_blocks_completion_id'), ['completion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_blocks_agent_execution_id'), ['agent_execution_id'], unique=False)

def downgrade() -> None:
    with op.batch_alter_table('completion_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_completion_blocks_completion_id'))
        batch_op.drop_index(batch_op.f('ix_completion_blocks_agent_execution_id'))

    op.drop_table('completion_blocks')
    # ### end Alembic commands ###
