"""files 
- type

Revision ID: 161909d75fe3
Revises: 8bd357a4b435
Create Date: 2024-08-13 12:41:23.333522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from app.core.types import get_uuid_column

# revision identifiers, used by Alembic.
revision: str = '161909d75fe3'
down_revision: Union[str, None] = '8bd357a4b435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'report_file_association',
        sa.Column('report_id', get_uuid_column(), nullable=False),
        sa.Column('file_id', get_uuid_column(), nullable=False),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('report_id', 'file_id')  # Composite primary key
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_file_association')
    # ### end Alembic commands ###
