"""rels migration

Revision ID: 222b03221e2c
Revises: d09c74cbca11
Create Date: 2024-08-09 22:20:26.949945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '222b03221e2c'
down_revision: Union[str, None] = 'd09c74cbca11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('x', sa.Integer(), nullable=False))
    op.add_column('widgets', sa.Column('y', sa.Integer(), nullable=False))
    op.add_column('widgets', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('widgets', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'height')
    op.drop_column('widgets', 'width')
    op.drop_column('widgets', 'y')
    op.drop_column('widgets', 'x')
    # ### end Alembic commands ###
