"""completion main router

Revision ID: 2e14945501c2
Revises: d9f81f7079ab
Create Date: 2024-08-25 13:33:28.824404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '2e14945501c2'
down_revision: Union[str, None] = 'd9f81f7079ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completions', sa.Column('main_router', sa.String(), nullable=False))
    op.execute("UPDATE completions SET main_router = 'table'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('completions', 'main_router')
    # ### end Alembic commands ###
