"""datasource tables

Revision ID: 30a368b87f58
Revises: 1c75bfbc8d10
Create Date: 2025-02-23 21:02:09.192000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a368b87f58'
down_revision: Union[str, None] = '1c75bfbc8d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource_tables',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('no_rows', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.String(length=36), nullable=False),
    sa.Column('pks', sa.JSON(), nullable=False),
    sa.Column('fks', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasource_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasource_tables_id'), ['id'], unique=True)


def downgrade() -> None:
    with op.batch_alter_table('datasource_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasource_tables_id'))

    op.drop_table('datasource_tables')
    # ### end Alembic commands ###
