"""add instruction reference

Revision ID: 37fe67baeb37
Revises: 874b2e21ffb7
Create Date: 2025-08-19 11:51:29.043554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fe67baeb37'
down_revision: Union[str, None] = '874b2e21ffb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction_references',
    sa.Column('instruction_id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.Column('display_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruction_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruction_references_id'), ['id'], unique=True)



def downgrade() -> None:
    with op.batch_alter_table('instruction_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruction_references_id'))

    op.drop_table('instruction_references')
