"""add user data source access

Revision ID: 3ec67dfd9ae6
Revises: 34e743df9be9
Create Date: 2025-09-23 22:35:06.269603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec67dfd9ae6'
down_revision: Union[str, None] = '34e743df9be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data_source_credentials',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('auth_mode', sa.String(length=64), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_data_source_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_data_source_credentials_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_data_source_credentials_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_data_source_credentials_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_data_source_credentials_user_id'), ['user_id'], unique=False)


    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_policy', sa.String(), nullable=False, server_default='system_only'))
        batch_op.add_column(sa.Column('allowed_user_auth_modes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('allowed_user_auth_modes')
        batch_op.drop_column('auth_policy')

    with op.batch_alter_table('user_data_source_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_data_source_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_data_source_credentials_organization_id'))
        batch_op.drop_index(batch_op.f('ix_user_data_source_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_user_data_source_credentials_data_source_id'))

    op.drop_table('user_data_source_credentials')
    # ### end Alembic commands ###
