"""add mentions

Revision ID: 42a7247575e0
Revises: 168fb2a83c58
Create Date: 2024-10-09 11:38:03.460286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '42a7247575e0'
down_revision: Union[str, None] = '168fb2a83c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('type', sa.Enum('FILE', 'MEMORY', 'DATA_SOURCE', name='mentiontype'), nullable=False),
    sa.Column('report_id', get_uuid_column(), nullable=False),
    sa.Column('object_id', get_uuid_column(), nullable=False),
    sa.Column('mention_content', sa.String(), nullable=False),
    sa.Column('completion_id', get_uuid_column(), nullable=False),
    sa.Column('id', get_uuid_column(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completion_id'], ['completions.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_id'), 'mentions', ['id'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_mentions_id'), table_name='mentions')
    op.drop_table('mentions')