"""user organization
- type

Revision ID: 4ad4807cbb69
Revises: a6f685fea35c
Create Date: 2024-08-18 11:59:45.920663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '4ad4807cbb69'
down_revision: Union[str, None] = 'a6f685fea35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', get_uuid_column(), primary_key=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
