"""add_dashboard_versions

Revision ID: 4e833275cd01
Revises: ceefdc68b0dc
Create Date: 2025-09-07 20:02:32.675982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e833275cd01'
down_revision: Union[str, None] = 'ceefdc68b0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_layout_versions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('theme_name', sa.String(), nullable=True),
    sa.Column('theme_overrides', sa.JSON(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_layout_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_layout_versions_id'), ['id'], unique=True)

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view', sa.JSON(), nullable=True))

    with op.batch_alter_table('text_widgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view', sa.JSON(), nullable=True))
    
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_name', sa.String(), nullable=True, default='default'))
        batch_op.add_column(sa.Column('theme_overrides', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:

    with op.batch_alter_table('text_widgets', schema=None) as batch_op:
        batch_op.drop_column('view')

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_column('view')

    with op.batch_alter_table('dashboard_layout_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_layout_versions_id'))

    op.drop_table('dashboard_layout_versions')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('theme_name')
        batch_op.drop_column('theme_overrides')

    # ### end Alembic commands ###
