"""llm usage record

Revision ID: 52668a7dca6d
Revises: 9e2b31aaa07e
Create Date: 2025-11-22 16:49:49.612379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52668a7dca6d'
down_revision: Union[str, None] = '9e2b31aaa07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_records',
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('scope_ref_id', sa.String(), nullable=True),
    sa.Column('llm_model_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('output_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_records_id'), ['id'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('llm_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_id'))

    op.drop_table('llm_usage_records')
    # ### end Alembic commands ###
