"""add org settings

Revision ID: 6b55dcdbf53f
Revises: f0dbe0e6e596
Create Date: 2025-03-30 20:24:57.970583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b55dcdbf53f'
down_revision: Union[str, None] = 'f0dbe0e6e596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_settings',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_settings_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_settings_id'))

    op.drop_table('organization_settings')
    # ### end Alembic commands ###
