"""add prompts

Revision ID: 6ca8f6939a3d
Revises: 2e14945501c2
Create Date: 2024-09-05 09:49:48.697106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '6ca8f6939a3d'
down_revision: Union[str, None] = '2e14945501c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_id', get_uuid_column(), nullable=True),
    sa.Column('organization_id', get_uuid_column(), nullable=True),
    sa.Column('id', get_uuid_column(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
