"""add ds memberships and public ds

Revision ID: 874b2e21ffb7
Revises: 107fc9d42143
Create Date: 2025-08-08 07:32:04.395329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874b2e21ffb7'
down_revision: Union[str, None] = '107fc9d42143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_memberships',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('principal_type', sa.String(), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'principal_type', 'principal_id', name='uq_data_source_membership')
    )
    with op.batch_alter_table('data_source_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_memberships_id'), ['id'], unique=True)

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('owner_user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_data_sources_owner_user_id', 'users', ['owner_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_constraint('fk_data_sources_owner_user_id', type_='foreignkey')
        batch_op.drop_column('owner_user_id')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('data_source_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_memberships_id'))

    op.drop_table('data_source_memberships')
    # ### end Alembic commands ###
