"""files 
- type

Revision ID: 8bd357a4b435
Revises: 53b26b0d0176
Create Date: 2024-08-13 11:28:42.692643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '8bd357a4b435'
down_revision: Union[str, None] = '53b26b0d0176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('id', get_uuid_column(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_content_type'), 'files', ['content_type'], unique=False)
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_index(op.f('ix_files_content_type'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
