"""report-data source association

Revision ID: 905a08bb2ca7
Revises: 6ffcc2857942
Create Date: 2024-08-20 13:30:06.475731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = '905a08bb2ca7'
down_revision: Union[str, None] = '6ffcc2857942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_data_source_association',
    sa.Column('report_id', get_uuid_column(), nullable=True),
    sa.Column('data_source_id', get_uuid_column(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_data_source_association')
    # ### end Alembic commands ###
