"""add llm sync to data sources

Revision ID: 9a4893c8b0ee
Revises: ca84ec3273b7
Create Date: 2025-09-18 09:02:44.666778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a4893c8b0ee'
down_revision: Union[str, None] = 'ca84ec3273b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_llm_sync', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('use_llm_sync')

    # ### end Alembic commands ###
