"""instruction labels

Revision ID: 9e2b31aaa07e
Revises: fb664b5328e0
Create Date: 2025-11-17 09:37:18.385487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e2b31aaa07e'
down_revision: Union[str, None] = 'fb664b5328e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction_labels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruction_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruction_labels_id'), ['id'], unique=True)

    op.create_table('instruction_label_association',
    sa.Column('instruction_id', sa.String(length=36), nullable=False),
    sa.Column('label_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['instruction_labels.id'], ),
    sa.PrimaryKeyConstraint('instruction_id', 'label_id')
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_table('instruction_label_association')
    with op.batch_alter_table('instruction_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruction_labels_id'))

    op.drop_table('instruction_labels')
    # ### end Alembic commands ###
