"""user name not unique
- type

Revision ID: a6f685fea35c
Revises: 21952d7521e4
Create Date: 2024-08-18 10:46:11.783849

"""
from typing import Sequence, Union
from app.core.types import get_uuid_column
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f685fea35c'
down_revision: Union[str, None] = '21952d7521e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_name', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_user_name', 'users', ['name'], unique=True)
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
