"""more

Revision ID: bab1312c9d43
Revises: 222b03221e2c
Create Date: 2024-08-10 10:51:47.344032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = 'bab1312c9d43'
down_revision: Union[str, None] = '222b03221e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'data')
    # ### end Alembic commands ###
