"""add_ae_and_reasoning_to_instructions

Revision ID: ceefdc68b0dc
Revises: 1576b701e34b
Create Date: 2025-09-06 16:59:45.618378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceefdc68b0dc'
down_revision: Union[str, None] = '1576b701e34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_execution_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('ai_source', sa.String(length=255), nullable=True, default=None))
        batch_op.add_column(sa.Column('trigger_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_instruction_agent_execution', 'agent_executions', ['agent_execution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instruction_agent_execution', type_='foreignkey')
        batch_op.drop_column('trigger_reason')
        batch_op.drop_column('agent_execution_id')
        batch_op.drop_column('ai_source')
    # ### end Alembic commands ###
