"""rels migration

Revision ID: d09c74cbca11
Revises: a2d893ef9090
Create Date: 2024-08-09 21:43:11.765155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09c74cbca11'
down_revision: Union[str, None] = 'a2d893ef9090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_reports_title', table_name='reports')
    # op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    # op.alter_column('steps', 'widget_id',
               # existing_type=sa.INTEGER(),
               # nullable=False)
    # op.drop_index('ix_steps_title', table_name='steps')
    # op.create_index(op.f('ix_steps_title'), 'steps', ['title'], unique=False)
    # op.create_index(op.f('ix_steps_id'), 'steps', ['id'], unique=False)
    # op.alter_column('widgets', 'report_id',
               # existing_type=sa.INTEGER(),
               # nullable=False)
    # op.drop_index('ix_widgets_title', table_name='widgets')
    # op.create_index(op.f('ix_widgets_title'), 'widgets', ['title'], unique=False)
    # op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # 
    # op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    # 
    # op.drop_index(op.f('ix_widgets_title'), table_name='widgets')
    # op.create_index('ix_widgets_title', 'widgets', ['title'], unique=True)
    # op.alter_column('widgets', 'report_id',
               # existing_type=sa.INTEGER(),
               # nullable=True)
    # op.drop_index(op.f('ix_steps_id'), table_name='steps')
    # op.drop_index(op.f('ix_steps_title'), table_name='steps')
    # op.create_index('ix_steps_title', 'steps', ['title'], unique=True)
    # op.alter_column('steps', 'widget_id',
               # existing_type=sa.INTEGER(),
               # nullable=True)
    # op.drop_index(op.f('ix_reports_title'), table_name='reports')
    # op.create_index('ix_reports_title', 'reports', ['title'], unique=True)
    # ### end Alembic commands ###
