"""step - type

Revision ID: d2b570e7bbe0
Revises: eb06fbd98645
Create Date: 2024-08-11 20:33:00.878265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import get_uuid_column


# revision identifiers, used by Alembic.
revision: str = 'd2b570e7bbe0'
down_revision: Union[str, None] = 'eb06fbd98645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('type', sa.String(), nullable=False, server_default="table"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'type')
    # ### end Alembic commands ###
