"""data model in step

Revision ID: d9f81f7079ab
Revises: 04c2c1e3b151
Create Date: 2024-08-24 11:54:10.262318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f81f7079ab'
down_revision: Union[str, None] = '04c2c1e3b151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('steps', sa.Column('data_model', sa.JSON(), nullable=True, default=dict))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('steps', 'data_model')
        # ### end Alembic commands ###
