"""add test models

Revision ID: da68823779da
Revises: 95de3b2ebc88
Create Date: 2025-11-04 12:53:19.765294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'da68823779da'
down_revision: Union[str, None] = '9479f7d83f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'test_suites' not in inspector.get_table_names():
        op.create_table('test_suites',
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('test_suites', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_test_suites_id'), ['id'], unique=True)
            batch_op.create_index(batch_op.f('ix_test_suites_organization_id'), ['organization_id'], unique=False)

    if 'test_cases' not in inspector.get_table_names():
        op.create_table('test_cases',
        sa.Column('suite_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('prompt_json', sa.JSON(), nullable=False),
        sa.Column('expectations_json', sa.JSON(), nullable=False),
        sa.Column('data_source_ids_json', sa.JSON(), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('test_cases', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_test_cases_id'), ['id'], unique=True)
            batch_op.create_index(batch_op.f('ix_test_cases_suite_id'), ['suite_id'], unique=False)

    if 'test_runs' not in inspector.get_table_names():
        op.create_table('test_runs',
        sa.Column('title', sa.String(), nullable=False),
        # A run can span multiple suites: persist a comma-separated list of suite IDs
        # for portability across SQLite and Postgres.
        sa.Column('suite_ids', sa.String(), nullable=False),
        sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
        sa.Column('trigger_reason', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('summary_json', sa.JSON(), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('test_runs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_test_runs_id'), ['id'], unique=True)
            batch_op.create_index(batch_op.f('ix_test_runs_requested_by_user_id'), ['requested_by_user_id'], unique=False)

    if 'test_results' not in inspector.get_table_names():
        op.create_table('test_results',
        sa.Column('run_id', sa.String(length=36), nullable=False),
        sa.Column('case_id', sa.String(length=36), nullable=False),
        sa.Column('head_completion_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('failure_reason', sa.String(), nullable=True),
        sa.Column('agent_execution_id', sa.String(length=36), nullable=True),
        sa.Column('report_id', sa.String(length=36), nullable=True),
        sa.Column('result_json', sa.JSON(), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ),
        sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ),
        sa.ForeignKeyConstraint(['head_completion_id'], ['completions.id'], ),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
        sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('test_results', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_test_results_agent_execution_id'), ['agent_execution_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_test_results_case_id'), ['case_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_test_results_head_completion_id'), ['head_completion_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_test_results_id'), ['id'], unique=True)
            batch_op.create_index(batch_op.f('ix_test_results_run_id'), ['run_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_test_results_report_id'), ['report_id'], unique=False)

    #reports_columns = [c['name'] for c in inspector.get_columns('reports')]
    #existing_indexes = [i['name'] for i in inspector.get_indexes('reports')]
    #ix_reports_report_type = op.f('ix_reports_report_type')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.String(), nullable=False, server_default='regular'))
        batch_op.create_index(op.f('ix_reports_report_type'), ['report_type'], unique=False)
    # ### end Alembic commands ###

    # Data backfill: create a default test suite per organization if none exist.
    # Works for both SQLite and Postgres by using SQLAlchemy core and reflection.
    try:
        bind = op.get_bind()
        inspector = sa.inspect(bind)
        table_names = set(inspector.get_table_names())
        if 'organizations' in table_names and 'test_suites' in table_names:
            metadata = sa.MetaData()
            metadata.bind = bind
            orgs = sa.Table('organizations', metadata, autoload_with=bind)
            suites = sa.Table('test_suites', metadata, autoload_with=bind)

            # Fetch all organizations
            org_rows = list(bind.execute(sa.select(orgs.c.id)))
            now = datetime.utcnow()
            for row in org_rows:
                org_id = row[0] if not hasattr(row, 'id') else row.id
                # Count suites for this org
                count_q = sa.select(sa.func.count()).select_from(suites).where(suites.c.organization_id == org_id)
                suite_count = bind.execute(count_q).scalar() or 0
                if suite_count == 0:
                    bind.execute(
                        suites.insert().values(
                            id=str(uuid.uuid4()),
                            organization_id=org_id,
                            name='Default',
                            description='Auto-created',
                            created_at=now,
                            updated_at=now,
                        )
                    )
    except Exception:
        # Best-effort backfill; ignore to avoid blocking schema upgrade on legacy data quirks
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_column('report_type')

    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_head_completion_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_case_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_agent_execution_id'))

    op.drop_table('test_results')
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_test_runs_id'))

    op.drop_table('test_runs')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_suite_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_id'))

    op.drop_table('test_cases')
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_suites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_test_suites_id'))

    op.drop_table('test_suites')
    # ### end Alembic commands ###
