"""external platform integrations

Revision ID: ef9ca851f6ea
Revises: b619d8681865
Create Date: 2025-07-09 10:52:59.287326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9ca851f6ea'
down_revision: Union[str, None] = 'b619d8681865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_platforms',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('platform_type', sa.String(), nullable=False),
    sa.Column('platform_config', sa.JSON(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_platforms_id'), ['id'], unique=True)

    op.create_table('external_user_mappings',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('platform_type', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=False),
    sa.Column('external_email', sa.String(), nullable=True),
    sa.Column('external_name', sa.String(), nullable=True),
    sa.Column('app_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'platform_type', 'external_user_id', name='unique_external_user'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('external_user_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_user_mappings_id'), ['id'], unique=True)

    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_platform', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_message_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_user_id', sa.String(), nullable=True))



def downgrade() -> None:

    with op.batch_alter_table('completions', schema=None) as batch_op:
        batch_op.drop_column('external_user_id')
        batch_op.drop_column('external_message_id')
        batch_op.drop_column('external_platform')

    with op.batch_alter_table('external_user_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_user_mappings_id'))

    op.drop_table('external_user_mappings')
    with op.batch_alter_table('external_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_platforms_id'))

    op.drop_table('external_platforms')
    # ### end Alembic commands ###
