"""indexing job + dbt resources

Revision ID: f0dbe0e6e596
Revises: 402e3481e1cb
Create Date: 2025-03-21 14:53:02.082498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dbe0e6e596'
down_revision: Union[str, None] = '402e3481e1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_indexing_jobs',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_resources', sa.Integer(), nullable=True),
    sa.Column('processed_resources', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('git_repository_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['git_repository_id'], ['git_repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metadata_indexing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_indexing_jobs_id'), ['id'], unique=True)

    op.create_table('dbt_resources',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('sql_content', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_indexing_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['metadata_indexing_job_id'], ['metadata_indexing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dbt_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dbt_resources_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:

    with op.batch_alter_table('dbt_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dbt_resources_id'))

    op.drop_table('dbt_resources')
    with op.batch_alter_table('metadata_indexing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_indexing_jobs_id'))

    op.drop_table('metadata_indexing_jobs')
    # ### end Alembic commands ###
