"""add context to data source

Revision ID: fd7dd5ccc203
Revises: 3422a3da5b2d
Create Date: 2024-11-20 16:31:45.812254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7dd5ccc203'
down_revision: Union[str, None] = '3422a3da5b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('context')

    # ### end Alembic commands ###
