apiVersion: v1
kind: Service
metadata:
  name: {{ include "bowapp.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bowapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "bowapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
